ARDUINO_DIR = /usr/share/arduino
AVR_TOOLS_DIR = /usr
USER_LIB_PATH = ./

ARDUINO_LIBS = Wire OneWire
BOARD_TAG = atmega328
MONITOR_PORT = /dev/ttyUSB0

EXTRA_FLAGS = -I../
EXTRA_CXXFLAGS = -std=c++11

include ./Arduino-Makefile/Arduino.mk
