#ifndef _THEME_H
#define _THEME_H

#define THEME_DEFAULT_COLOUR (0x0000)
#define THEME_DEFAULT_BACKGROUND_COLOUR (0xffff)

#define THEME_CLIENT_AREA_BACKGROUND_COLOUR THEME_DEFAULT_BACKGROUND_COLOUR
#define THEME_CLIENT_AREA_BORDER_COLOUR THEME_DEFAULT_COLOUR
#define THEME_CLIENT_AREA_COLOUR THEME_DEFAULT_COLOUR

#define THEME_TH_BACKGROUND_COLOUR (0xbebf)
#define THEME_TH_COLOUR THEME_DEFAULT_COLOUR
#define THEME_TR_COLOUR THEME_DEFAULT_COLOUR
#define THEME_TR_ODD_BACKGROUND_COLOUR THEME_DEFAULT_BACKGROUND_COLOUR
#define THEME_TR_ODD_COLOUR THEME_TR_COLOUR
#define THEME_TR_EVEN_BACKGROUND_COLOUR (0xdf5e)
#define THEME_TR_EVEN_COLOUR THEME_TR_COLOUR

#define THEME_BACKDROP_BACKGROUND_COLOUR (0x0000)
#define THEME_CLOCK_COLOUR (0xffff)

#define THEME_H1_BACKGROUND_COLOUR (0xffff)
#define THEME_H1_COLOUR (0x0000)
#define THEME_H1_BORDER_COLOUR (0x0000)

#define THEME_TAB_BACKGROUND_COLOUR (0x0000)
#define THEME_TAB_BORDER_COLOUR (0x7bef)
#define THEME_TAB_COLOUR (0xffff)
#define THEME_TAB_ACTIVE_BACKGROUND_COLOUR (0xffff)
#define THEME_TAB_ACTIVE_BORDER_COLOUR (0x0000)
#define THEME_TAB_ACTIVE_COLOUR (0x0000)

#endif
